export const dom = {
    attributeGrid: document.querySelector('.attribute-grid'),
    pointsDisplay: document.getElementById('points-remaining'),
    skillsContainer: document.getElementById('skills-container'),
    coreSkillPointsDisplay: document.getElementById('core-skill-points-remaining'),
    pickupSkillPointsDisplay: document.getElementById('pickup-skill-points-remaining'),
    rerollHistoryBtn: document.getElementById('reroll-history-btn'), // AJOUT
    rerollAttributesBtn: document.getElementById('reroll-attributes-btn'),
    rerollSkillsBtn: document.getElementById('reroll-skills-btn'),
    exportCsvBtn: document.getElementById('export-csv-btn'),
    downloadBtn: document.getElementById('download-btn'),
    printBtn: document.getElementById('print-btn'),
    identity: {
        name: document.getElementById('char-name'),
        handle: document.getElementById('char-handle'),
        lifepath: document.getElementById('lifepath')
    },
    history: {
        style: document.getElementById('char-style'),
        hair: document.getElementById('char-hair'),
        accessory: document.getElementById('char-accessory'),
        origin: document.getElementById('char-origin'),
        language: document.getElementById('char-language'),
        csp: document.getElementById('char-csp'),
        childhood: document.getElementById('char-childhood'),
        familyFate: document.getElementById('char-family-fate'),
        siblings: document.getElementById('char-siblings'),
    },
    summary: {
        name: document.getElementById('summary-name'),
        handle: document.getElementById('summary-handle'),
        lifepath: document.getElementById('summary-lifepath'),
        style: document.getElementById('summary-style'),
        hair: document.getElementById('summary-hair'),
        accessory: document.getElementById('summary-accessory'),
        origin: document.getElementById('summary-origin'),
        language: document.getElementById('summary-language'),
        csp: document.getElementById('summary-csp'),
        childhood: document.getElementById('summary-childhood'),
        familyFate: document.getElementById('summary-family-fate'),
        siblings: document.getElementById('summary-siblings'),
        attributes: document.getElementById('summary-attributes'),
        humanity: document.getElementById('summary-humanity'),
        skills: document.getElementById('summary-skills'),
    }
};